/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as R50formulareIndexImport } from './routes/50_formulare/index'
import { Route as R40transitionsIndexImport } from './routes/40_transitions/index'
import { Route as R32metatitleIndexImport } from './routes/32_meta_title/index'
import { Route as R30stylesheetsundlinksIndexImport } from './routes/30_stylesheets_und_links/index'
import { Route as R29assetloadingIndexImport } from './routes/29_asset_loading/index'
import { Route as R27promiserendernexotischIndexImport } from './routes/27promise_rendern_exotisch/index'
import { Route as R25compilerIndexImport } from './routes/25_compiler/index'
import { Route as R20usecontextIndexImport } from './routes/20_use_context/index'
import { Route as R15usepromiseconditionalIndexImport } from './routes/15use_promise_conditional/index'
import { Route as R12usepromiseIndexImport } from './routes/12use_promise/index'
import { Route as R10suspenseIndexImport } from './routes/10suspense/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const R50formulareIndexRoute = R50formulareIndexImport.update({
  path: '/50_formulare/',
  getParentRoute: () => rootRoute,
} as any)

const R40transitionsIndexRoute = R40transitionsIndexImport.update({
  path: '/40_transitions/',
  getParentRoute: () => rootRoute,
} as any)

const R32metatitleIndexRoute = R32metatitleIndexImport.update({
  path: '/32_meta_title/',
  getParentRoute: () => rootRoute,
} as any)

const R30stylesheetsundlinksIndexRoute =
  R30stylesheetsundlinksIndexImport.update({
    path: '/30_stylesheets_und_links/',
    getParentRoute: () => rootRoute,
  } as any)

const R29assetloadingIndexRoute = R29assetloadingIndexImport.update({
  path: '/29_asset_loading/',
  getParentRoute: () => rootRoute,
} as any)

const R27promiserendernexotischIndexRoute =
  R27promiserendernexotischIndexImport.update({
    path: '/27promise_rendern_exotisch/',
    getParentRoute: () => rootRoute,
  } as any)

const R25compilerIndexRoute = R25compilerIndexImport.update({
  path: '/25_compiler/',
  getParentRoute: () => rootRoute,
} as any)

const R20usecontextIndexRoute = R20usecontextIndexImport.update({
  path: '/20_use_context/',
  getParentRoute: () => rootRoute,
} as any)

const R15usepromiseconditionalIndexRoute =
  R15usepromiseconditionalIndexImport.update({
    path: '/15use_promise_conditional/',
    getParentRoute: () => rootRoute,
  } as any)

const R12usepromiseIndexRoute = R12usepromiseIndexImport.update({
  path: '/12use_promise/',
  getParentRoute: () => rootRoute,
} as any)

const R10suspenseIndexRoute = R10suspenseIndexImport.update({
  path: '/10suspense/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/10suspense/': {
      id: '/10suspense/'
      path: '/10suspense'
      fullPath: '/10suspense'
      preLoaderRoute: typeof R10suspenseIndexImport
      parentRoute: typeof rootRoute
    }
    '/12use_promise/': {
      id: '/12use_promise/'
      path: '/12use_promise'
      fullPath: '/12use_promise'
      preLoaderRoute: typeof R12usepromiseIndexImport
      parentRoute: typeof rootRoute
    }
    '/15use_promise_conditional/': {
      id: '/15use_promise_conditional/'
      path: '/15use_promise_conditional'
      fullPath: '/15use_promise_conditional'
      preLoaderRoute: typeof R15usepromiseconditionalIndexImport
      parentRoute: typeof rootRoute
    }
    '/20_use_context/': {
      id: '/20_use_context/'
      path: '/20_use_context'
      fullPath: '/20_use_context'
      preLoaderRoute: typeof R20usecontextIndexImport
      parentRoute: typeof rootRoute
    }
    '/25_compiler/': {
      id: '/25_compiler/'
      path: '/25_compiler'
      fullPath: '/25_compiler'
      preLoaderRoute: typeof R25compilerIndexImport
      parentRoute: typeof rootRoute
    }
    '/27promise_rendern_exotisch/': {
      id: '/27promise_rendern_exotisch/'
      path: '/27promise_rendern_exotisch'
      fullPath: '/27promise_rendern_exotisch'
      preLoaderRoute: typeof R27promiserendernexotischIndexImport
      parentRoute: typeof rootRoute
    }
    '/29_asset_loading/': {
      id: '/29_asset_loading/'
      path: '/29_asset_loading'
      fullPath: '/29_asset_loading'
      preLoaderRoute: typeof R29assetloadingIndexImport
      parentRoute: typeof rootRoute
    }
    '/30_stylesheets_und_links/': {
      id: '/30_stylesheets_und_links/'
      path: '/30_stylesheets_und_links'
      fullPath: '/30_stylesheets_und_links'
      preLoaderRoute: typeof R30stylesheetsundlinksIndexImport
      parentRoute: typeof rootRoute
    }
    '/32_meta_title/': {
      id: '/32_meta_title/'
      path: '/32_meta_title'
      fullPath: '/32_meta_title'
      preLoaderRoute: typeof R32metatitleIndexImport
      parentRoute: typeof rootRoute
    }
    '/40_transitions/': {
      id: '/40_transitions/'
      path: '/40_transitions'
      fullPath: '/40_transitions'
      preLoaderRoute: typeof R40transitionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/50_formulare/': {
      id: '/50_formulare/'
      path: '/50_formulare'
      fullPath: '/50_formulare'
      preLoaderRoute: typeof R50formulareIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/10suspense': typeof R10suspenseIndexRoute
  '/12use_promise': typeof R12usepromiseIndexRoute
  '/15use_promise_conditional': typeof R15usepromiseconditionalIndexRoute
  '/20_use_context': typeof R20usecontextIndexRoute
  '/25_compiler': typeof R25compilerIndexRoute
  '/27promise_rendern_exotisch': typeof R27promiserendernexotischIndexRoute
  '/29_asset_loading': typeof R29assetloadingIndexRoute
  '/30_stylesheets_und_links': typeof R30stylesheetsundlinksIndexRoute
  '/32_meta_title': typeof R32metatitleIndexRoute
  '/40_transitions': typeof R40transitionsIndexRoute
  '/50_formulare': typeof R50formulareIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/10suspense': typeof R10suspenseIndexRoute
  '/12use_promise': typeof R12usepromiseIndexRoute
  '/15use_promise_conditional': typeof R15usepromiseconditionalIndexRoute
  '/20_use_context': typeof R20usecontextIndexRoute
  '/25_compiler': typeof R25compilerIndexRoute
  '/27promise_rendern_exotisch': typeof R27promiserendernexotischIndexRoute
  '/29_asset_loading': typeof R29assetloadingIndexRoute
  '/30_stylesheets_und_links': typeof R30stylesheetsundlinksIndexRoute
  '/32_meta_title': typeof R32metatitleIndexRoute
  '/40_transitions': typeof R40transitionsIndexRoute
  '/50_formulare': typeof R50formulareIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/10suspense/': typeof R10suspenseIndexRoute
  '/12use_promise/': typeof R12usepromiseIndexRoute
  '/15use_promise_conditional/': typeof R15usepromiseconditionalIndexRoute
  '/20_use_context/': typeof R20usecontextIndexRoute
  '/25_compiler/': typeof R25compilerIndexRoute
  '/27promise_rendern_exotisch/': typeof R27promiserendernexotischIndexRoute
  '/29_asset_loading/': typeof R29assetloadingIndexRoute
  '/30_stylesheets_und_links/': typeof R30stylesheetsundlinksIndexRoute
  '/32_meta_title/': typeof R32metatitleIndexRoute
  '/40_transitions/': typeof R40transitionsIndexRoute
  '/50_formulare/': typeof R50formulareIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/10suspense'
    | '/12use_promise'
    | '/15use_promise_conditional'
    | '/20_use_context'
    | '/25_compiler'
    | '/27promise_rendern_exotisch'
    | '/29_asset_loading'
    | '/30_stylesheets_und_links'
    | '/32_meta_title'
    | '/40_transitions'
    | '/50_formulare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/10suspense'
    | '/12use_promise'
    | '/15use_promise_conditional'
    | '/20_use_context'
    | '/25_compiler'
    | '/27promise_rendern_exotisch'
    | '/29_asset_loading'
    | '/30_stylesheets_und_links'
    | '/32_meta_title'
    | '/40_transitions'
    | '/50_formulare'
  id:
    | '__root__'
    | '/'
    | '/10suspense/'
    | '/12use_promise/'
    | '/15use_promise_conditional/'
    | '/20_use_context/'
    | '/25_compiler/'
    | '/27promise_rendern_exotisch/'
    | '/29_asset_loading/'
    | '/30_stylesheets_und_links/'
    | '/32_meta_title/'
    | '/40_transitions/'
    | '/50_formulare/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R10suspenseIndexRoute: typeof R10suspenseIndexRoute
  R12usepromiseIndexRoute: typeof R12usepromiseIndexRoute
  R15usepromiseconditionalIndexRoute: typeof R15usepromiseconditionalIndexRoute
  R20usecontextIndexRoute: typeof R20usecontextIndexRoute
  R25compilerIndexRoute: typeof R25compilerIndexRoute
  R27promiserendernexotischIndexRoute: typeof R27promiserendernexotischIndexRoute
  R29assetloadingIndexRoute: typeof R29assetloadingIndexRoute
  R30stylesheetsundlinksIndexRoute: typeof R30stylesheetsundlinksIndexRoute
  R32metatitleIndexRoute: typeof R32metatitleIndexRoute
  R40transitionsIndexRoute: typeof R40transitionsIndexRoute
  R50formulareIndexRoute: typeof R50formulareIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R10suspenseIndexRoute: R10suspenseIndexRoute,
  R12usepromiseIndexRoute: R12usepromiseIndexRoute,
  R15usepromiseconditionalIndexRoute: R15usepromiseconditionalIndexRoute,
  R20usecontextIndexRoute: R20usecontextIndexRoute,
  R25compilerIndexRoute: R25compilerIndexRoute,
  R27promiserendernexotischIndexRoute: R27promiserendernexotischIndexRoute,
  R29assetloadingIndexRoute: R29assetloadingIndexRoute,
  R30stylesheetsundlinksIndexRoute: R30stylesheetsundlinksIndexRoute,
  R32metatitleIndexRoute: R32metatitleIndexRoute,
  R40transitionsIndexRoute: R40transitionsIndexRoute,
  R50formulareIndexRoute: R50formulareIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/10suspense/",
        "/12use_promise/",
        "/15use_promise_conditional/",
        "/20_use_context/",
        "/25_compiler/",
        "/27promise_rendern_exotisch/",
        "/29_asset_loading/",
        "/30_stylesheets_und_links/",
        "/32_meta_title/",
        "/40_transitions/",
        "/50_formulare/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/10suspense/": {
      "filePath": "10suspense/index.tsx"
    },
    "/12use_promise/": {
      "filePath": "12use_promise/index.tsx"
    },
    "/15use_promise_conditional/": {
      "filePath": "15use_promise_conditional/index.tsx"
    },
    "/20_use_context/": {
      "filePath": "20_use_context/index.tsx"
    },
    "/25_compiler/": {
      "filePath": "25_compiler/index.tsx"
    },
    "/27promise_rendern_exotisch/": {
      "filePath": "27promise_rendern_exotisch/index.tsx"
    },
    "/29_asset_loading/": {
      "filePath": "29_asset_loading/index.tsx"
    },
    "/30_stylesheets_und_links/": {
      "filePath": "30_stylesheets_und_links/index.tsx"
    },
    "/32_meta_title/": {
      "filePath": "32_meta_title/index.tsx"
    },
    "/40_transitions/": {
      "filePath": "40_transitions/index.tsx"
    },
    "/50_formulare/": {
      "filePath": "50_formulare/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
